import { describe, it, expect, vi, beforeEach } from 'vitest';
import fs from 'fs-extra';
import path from 'path';
import { StructuralMarkdownMiddleware } from '../src/middleware/agentic/structural-middleware.js';
import type { PipelineContext } from '../src/pipeline/middleware.js';

vi.mock('fs-extra', () => ({
    default: {
        pathExists: vi.fn(),
        readFile: vi.fn(),
    },
    pathExists: vi.fn(),
    readFile: vi.fn(),
}));

describe('StructuralMarkdownMiddleware Unit Tests', () => {
    let middleware: StructuralMarkdownMiddleware;
    let mockContext: PipelineContext;

    beforeEach(() => {
        middleware = new StructuralMarkdownMiddleware();
        mockContext = {
            request: {
                messages: [{ role: 'user', content: 'hello' }],
                sessionId: 'test-session',
                agentic: true, // v1.0.4 mandatory flag
            },
            storage: {
                get: vi.fn(),
                set: vi.fn(),
            },
        } as any;
        vi.clearAllMocks();
    });

    it('should correctly aggregate all structural state files', async () => {
        const mockFiles: Record<string, string> = {
            'plan.md': '# Mission Plan\nPlan content',
            'tasks.md': '# Task Progress\nTask content',
            'queues.json': JSON.stringify({
                nowQueue: ['task1'],
                nextQueue: ['task2']
            }),
            'knowledge.md': '# Knowledge\nKnowledge content',
        };

        (fs.pathExists as any).mockImplementation(async (p: string) => {
            const basename = path.basename(p);
            return !!mockFiles[basename];
        });

        (fs.readFile as any).mockImplementation(async (p: string) => {
            const basename = path.basename(p);
            return mockFiles[basename];
        });

        await middleware.execute(mockContext, async () => {});

        const lastMessage = mockContext.request.messages[mockContext.request.messages.length - 1];
        expect(lastMessage.content).toContain('## MISSION PLAN');
        expect(lastMessage.content).toContain('Plan content');
        expect(lastMessage.content).toContain('## ACTIVE TASKS');
        expect(lastMessage.content).toContain('Task content');
        expect(lastMessage.content).toContain('## TASK QUEUE');
        expect(lastMessage.content).toContain('**Now:**      task1');
        expect(lastMessage.content).toContain('## SESSION KNOWLEDGE');
    });

    it('should ignore empty scaffolds', async () => {
        const mockFiles: Record<string, string> = {
            'plan.md': '<!-- Auto-generated by Agentic Middleware -->\n# MISSION PLAN', // Empty scaffold minus headings
            'knowledge.md': '# Real Content\nThis is some substantive text.',
        };

        (fs.pathExists as any).mockImplementation(async (p: string) => {
            const basename = path.basename(p);
            return !!mockFiles[basename];
        });

        (fs.readFile as any).mockImplementation(async (p: string) => {
            const basename = path.basename(p);
            return mockFiles[basename];
        });

        await middleware.execute(mockContext, async () => {});

        const lastMessage = mockContext.request.messages[mockContext.request.messages.length - 1];
        expect(lastMessage.content).not.toContain('## MISSION PLAN');
        expect(lastMessage.content).toContain('## SESSION KNOWLEDGE');
        expect(lastMessage.content).toContain('# Real Content');
    });

    it('should enforce security boundaries and reject path traversal', async () => {
        // The regex v1.0.4 should reject this BEFORE file access
        (mockContext.request as any).sessionId = '../../etc/passwd';
        
        await middleware.execute(mockContext, async () => {});
        
        expect(fs.pathExists).not.toHaveBeenCalled();
    });

    it('should reject invalid sessionId characters', async () => {
        (mockContext.request as any).sessionId = 'session!@#';
        
        await middleware.execute(mockContext, async () => {});
        
        expect(fs.pathExists).not.toHaveBeenCalled();
    });
});
