import { promises as fs } from 'fs';
import path from 'path';
import { LRUCache } from 'lru-cache';
import { getIntelligentSystemPrompt } from './prompts.js';
import type { Middleware, PipelineContext, NextFunction } from '../../pipeline/middleware.js';
import { memoryManager } from '../../memory/index.js';
import { WorkspaceScanner } from '../../cache/workspace.js';
import { getMessageContent } from '../../utils/MessageUtils.js';

const workspaceScanner = new WorkspaceScanner(process.cwd());


interface QueueState {
    nowQueue: string[];
    nextQueue: string[];
    blockedQueue: string[];
    improveQueue: string[];
}

/**
 * Memory Management: Using LRUCache instead of Map to prevent leaks in high-concurrency environments.
 * Max 500 active sessions, 24h TTL.
 */
const queues = new LRUCache<string, QueueState>({
    max: 500,
    ttl: 1000 * 60 * 60 * 24,
});

function getQueues(sessionId: string): QueueState {
    let state = queues.get(sessionId);
    if (!state) {
        state = {
            nowQueue: [],
            nextQueue: [],
            blockedQueue: [],
            improveQueue: [],
        };
        queues.set(sessionId, state);
    }
    return state;
}

/**
 * Async Persistence: Prevents event-loop blocking.
 */
async function persistQueues(sessionId: string, projectDir: string): Promise<void> {
    const state = getQueues(sessionId);
    try {
        await fs.writeFile(
            path.join(projectDir, 'queues.json'),
            JSON.stringify(state, null, 2),
            'utf-8',
        );
    } catch {
        // non-fatal: in-memory state is still maintained
    }
}

/**
 * Async Project Setup: Ensures session boundaries and initializes state files.
 */
async function ensureProjectFiles(sessionId: string): Promise<string> {
    const projectDir = path.join(process.cwd(), 'data', 'projects', sessionId);
    await fs.mkdir(projectDir, { recursive: true });

    const files: Record<string, string> = {
        'plan.md': '# Plan\n\n<!-- Auto-generated by Agentic Middleware -->\n',
        'tasks.md': '# Tasks\n\n<!-- Auto-generated by Agentic Middleware -->\n',
        'knowledge.md': '# Knowledge\n\n<!-- Auto-generated by Agentic Middleware -->\n',
    };

    for (const [name, content] of Object.entries(files)) {
        const filePath = path.join(projectDir, name);
        try {
            await fs.access(filePath);
        } catch {
            await fs.writeFile(filePath, content, 'utf-8');
        }
    }

    return projectDir;
}

function decomposeGoal(goal: string): string[] {
    const lines = goal
        .split(/\n+/)
        .map(l => l.replace(/^\s*\d+[.)]\s*/, '').trim())
        .filter(l => l.length > 0);
    return lines.length > 1 ? lines : [goal];
}

async function prependSystemPrompt(
    context: PipelineContext,
    userContent?: string,
    explicitKeywords?: string[],
    memoryContext?: string
): Promise<void> {
    const messages = context.request.messages;
    if (!messages || messages.length === 0) return;

    const dynamicPrompt = await getIntelligentSystemPrompt(userContent, explicitKeywords, memoryContext);
    // v1.0.4 optimization: Force HIGH-LEVEL STEPS section (max 4 items) to constrain iteration
    const highLevelStepsSection = `\n\n## HIGH-LEVEL STEPS\nWhen responding to a task, always begin with a numbered list of at most **4** high-level steps. Example:\n1. Understand the task\n2. Implement the core change\n3. Validate correctness\n4. Summarize\nDo not list more than 4 steps.`;
    const hasSystem = messages[0].role === 'system';

    if (hasSystem) {
        messages[0] = {
            ...messages[0],
            content: `${dynamicPrompt}${highLevelStepsSection}\n\n${messages[0].content}`,
        };
    } else {
        messages.unshift({ role: 'system', content: `${dynamicPrompt}${highLevelStepsSection}` });
    }
}

function getResponseContent(context: PipelineContext): string | undefined {
    const rawContent = context.response?.choices?.[0]?.message?.content;
    return rawContent ? getMessageContent(rawContent) : undefined;
}

function verifySelf(content: string): string {
    if (!content || content.trim().length === 0) {
        return 'FAIL: empty response';
    }
    const errorPatterns = /\b(error|exception|failed|undefined|null)\b/i;
    if (errorPatterns.test(content.slice(0, 100))) {
        return 'FAIL: response starts with error indicator';
    }
    return 'PASS';
}

/**
 * Detect whether a user message contains a research or external-knowledge request.
 * These patterns indicate the agent may invoke external search, browse, or retrieve
 * information from outside the context window.
 *
 * Validation is logged explicitly so agents can confirm the step was intentional,
 * reducing hallucination risk when external sources are consulted.
 */
function detectResearchIntent(content: string): boolean {
    const researchPatterns = [
        /\b(search|look up|find|research|browse|retrieve|fetch|crawl|scrape)\b/i,
        /\b(what is|who is|when did|where is|how does|explain|describe|summarize)\b/i,
        /\b(latest|recent|current|today|news|update|version)\b/i,
        /\b(according to|based on|reference|source|documentation|docs)\b/i,
        /\b(web search|internet|online|URL|http|www\.)\b/i,
    ];
    return researchPatterns.some((p) => p.test(content));
}

function logResearchValidation(sessionId: string, userContent: string, step: string): void {
    const timestamp = new Date().toISOString();
    console.error(
        `[AgenticMiddleware][RESEARCH-VALIDATION] session=${sessionId} step="${step}" ` +
        `timestamp=${timestamp} intent_detected=true ` +
        `query_preview="${getMessageContent(userContent).slice(0, 120).replace(/\n/g, ' ')}..."`
    );
}

export class AgenticMiddleware implements Middleware {
    name = 'AgenticMiddleware';

    // v1.0.4 optimization: Cap decomposed plan to 4 high-level steps to prevent over-iteration
    private limitSubtasks(plan: string): string {
        const steps = plan.split('\n- ').filter(s => s.trim().length > 0);
        if (steps.length > 4) {
            return steps.slice(0, 4).join('\n- ') + '\n\n(Note: Limited to 4 high-level steps for efficiency. Remaining steps deferred to next iteration.)';
        }
        return plan;
    }

    async execute(context: PipelineContext, next: NextFunction): Promise<void> {
        console.time('agentic-middleware');
        // Dual-Mode Trigger: Global Env OR Per-Request Flag
        const isAgenticExplicitlyRequested = context.agentic === true || context.request?.agentic === true;
        if (process.env.ENABLE_AGENTIC_MIDDLEWARE !== 'true' && !isAgenticExplicitlyRequested) {
            await next();
            console.timeEnd('agentic-middleware');
            return;
        }

        // Hardened Session ID: Must be provided for agentic state to exist
        const sessionId: string | undefined = context.sessionId || (context.request as any).sessionId;

        if (!sessionId) {
            console.error('[AgenticMiddleware] Mandatory sessionId missing. Bypassing agentic layer to prevent data leakage and disk pollution.');
            await next();
            console.timeEnd('agentic-middleware');
            return;
        }

        // Resolve workspace hash for context lookup and safe pathing
        let wsHash: string | undefined;
        if (context.workspaceRoot) {
            try {
                wsHash = workspaceScanner.getWorkspaceHash(context.workspaceRoot);
            } catch (err) {
                console.error(`[AgenticMiddleware] Failed to derive workspace hash: ${err}`);
            }
        }


        const projectDir = await ensureProjectFiles(sessionId);
        const q = getQueues(sessionId);

        // Prepend system prompt with user context if available
        const userMessage = context.request.messages.find(m => m.role === 'user');
        const userContent = userMessage ? String(userMessage.content) : undefined;

        // Retrieve relevant workspace memory context
        let memoryContext: string | undefined;
        if (wsHash) {
            try {
                console.error(`[AgenticMiddleware][DEBUG] Searching for wsHash=${wsHash} query="${userContent}"`);
                const memoryResults = await memoryManager.search(wsHash, userContent);
                console.error(`[AgenticMiddleware][DEBUG] Found ${memoryResults.length} memory results`);
                if (Array.isArray(memoryResults) && memoryResults.length > 0) {
                    // Limit to top 5 results and format as bullet points
                    memoryContext = memoryResults
                        .slice(0, 5)
                        .map(m => `- ${typeof m === 'string' ? m : JSON.stringify(m)}`)
                        .join('\n');
                }
            } catch (err) {
                console.error(`[AgenticMiddleware] Memory lookup failed: ${err}`);
            }
        }



        try {
            await prependSystemPrompt(context, userContent, context.keywords, memoryContext);
        } catch (err) {
            console.error(`[AgenticMiddleware] Error prepending system prompt: ${err}`);
            // Continue without the prepended prompt
        }

        // Research validation: detect and log if this request involves external knowledge lookup.
        // This provides an explicit audit trail to reduce agent ambiguity and hallucination risk.
        if (userContent && detectResearchIntent(userContent)) {
            logResearchValidation(sessionId, userContent, 'pre-execution-research-detection');
        }


        // Task decomposition: Only perform if nowQueue is empty to prevent multi-turn duplication
        if (userContent && q.nowQueue.length === 0) {
            const steps = decomposeGoal(userContent);

            // v1.0.4 optimization: Apply subtask limit before queuing to prevent over-iteration
            const rawPlan = steps.join('\n- ');
            const limitedPlan = this.limitSubtasks(rawPlan);
            const limitedSteps = limitedPlan.split('\n- ').filter(s => s.trim().length > 0 && !s.startsWith('(Note:'));
            q.nowQueue.push(...limitedSteps);
        }

        await persistQueues(sessionId, projectDir);

        // v1.0.4 optimization: Track iteration count per session for early-exit logic
        const iterationCountKey = `_iteration_${sessionId}`;
        const iterationCount: number = (context[iterationCountKey] as number | undefined) ?? 0;
        context[iterationCountKey] = iterationCount + 1;

        // Execute the pipeline
        await next();

        // Verification and queue update
        const responseContent = getResponseContent(context);
        if (responseContent) {
            const verifyResult = verifySelf(responseContent);

            if (verifyResult.startsWith('FAIL')) {
                q.improveQueue.push(verifyResult);
                console.error(`[AgenticMiddleware][VERIFY] session=${sessionId} result="${verifyResult}"`);
            }

            // Post-execution research validation: confirm response is grounded
            if (userContent && detectResearchIntent(userContent)) {
                logResearchValidation(sessionId, responseContent, 'post-execution-response-grounding-check');
            }

            // v1.0.4 optimization: Compute a simple confidence score from response quality
            const confidenceScore = verifyResult === 'PASS' ? 0.9 : 0.4;

            // v1.0.4 optimization: Early exit if confidence is high or max iterations reached
            if (confidenceScore > 0.85 || iterationCount >= 3) {
                console.info(`[AgenticMiddleware] Early exit: confidence=${confidenceScore} iterations=${iterationCount}`);
                q.nowQueue = [];
            }

            // Store a snapshot for observability (cloned to avoid post-shift mutation in traces)
            context['agenticQueues'] = JSON.parse(JSON.stringify(getQueues(sessionId)));
        }

        if (q.nowQueue.length > 0) {
            q.nowQueue.shift();
        }
        await persistQueues(sessionId, projectDir);
        console.timeEnd('agentic-middleware');
    }
}
