import { promises as fs } from 'fs';
import path from 'path';
import { LRUCache } from 'lru-cache';
import { getIntelligentSystemPrompt } from './prompts.js';
import type { Middleware, PipelineContext, NextFunction } from '../../pipeline/middleware.js';


interface QueueState {
    nowQueue: string[];
    nextQueue: string[];
    blockedQueue: string[];
    improveQueue: string[];
}

/**
 * Memory Management: Using LRUCache instead of Map to prevent leaks in high-concurrency environments.
 * Max 500 active sessions, 24h TTL.
 */
const queues = new LRUCache<string, QueueState>({
    max: 500,
    ttl: 1000 * 60 * 60 * 24,
});

function getQueues(sessionId: string): QueueState {
    let state = queues.get(sessionId);
    if (!state) {
        state = {
            nowQueue: [],
            nextQueue: [],
            blockedQueue: [],
            improveQueue: [],
        };
        queues.set(sessionId, state);
    }
    return state;
}

/**
 * Async Persistence: Prevents event-loop blocking.
 */
async function persistQueues(sessionId: string, projectDir: string): Promise<void> {
    const state = getQueues(sessionId);
    try {
        await fs.writeFile(
            path.join(projectDir, 'queues.json'),
            JSON.stringify(state, null, 2),
            'utf-8',
        );
    } catch {
        // non-fatal: in-memory state is still maintained
    }
}

/**
 * Async Project Setup: Ensures session boundaries and initializes state files.
 */
async function ensureProjectFiles(sessionId: string): Promise<string> {
    const projectDir = path.join(process.cwd(), 'projects', sessionId);
    await fs.mkdir(projectDir, { recursive: true });

    const files: Record<string, string> = {
        'plan.md': '# Plan\n\n<!-- Auto-generated by Agentic Middleware -->\n',
        'tasks.md': '# Tasks\n\n<!-- Auto-generated by Agentic Middleware -->\n',
        'knowledge.md': '# Knowledge\n\n<!-- Auto-generated by Agentic Middleware -->\n',
    };

    for (const [name, content] of Object.entries(files)) {
        const filePath = path.join(projectDir, name);
        try {
            await fs.access(filePath);
        } catch {
            await fs.writeFile(filePath, content, 'utf-8');
        }
    }

    return projectDir;
}

function decomposeGoal(goal: string): string[] {
    const lines = goal
        .split(/\n+/)
        .map(l => l.replace(/^\s*\d+[.)]\s*/, '').trim())
        .filter(l => l.length > 0);
    return lines.length > 1 ? lines : [goal];
}

async function prependSystemPrompt(context: PipelineContext, userContent?: string): Promise<void> {
    const messages = context.request.messages;
    if (!messages || messages.length === 0) return;

    const dynamicPrompt = await getIntelligentSystemPrompt(userContent);
    const hasSystem = messages[0].role === 'system';
    
    if (hasSystem) {
        messages[0] = {
            ...messages[0],
            content: `${dynamicPrompt}\n\n${messages[0].content}`,
        };
    } else {
        messages.unshift({ role: 'system', content: dynamicPrompt });
    }
}

function getResponseContent(context: PipelineContext): string | undefined {
    return context.response?.choices?.[0]?.message?.content;
}

function verifySelf(content: string): string {
    if (!content || content.trim().length === 0) {
        return 'FAIL: empty response';
    }
    const errorPatterns = /\b(error|exception|failed|undefined|null)\b/i;
    if (errorPatterns.test(content.slice(0, 100))) {
        return 'FAIL: response starts with error indicator';
    }
    return 'PASS';
}

export class AgenticMiddleware implements Middleware {
    name = 'AgenticMiddleware';

    async execute(context: PipelineContext, next: NextFunction): Promise<void> {
        // Dual-Mode Trigger: Global Env OR Per-Request Flag
        const isAgenticExplicitlyRequested = context.agentic === true || context.request?.agentic === true;
        if (process.env.ENABLE_AGENTIC_MIDDLEWARE !== 'true' && !isAgenticExplicitlyRequested) {
            await next();
            return;
        }

        // Hardened Session ID: Must be provided for agentic state to exist
        const sessionId: string | undefined = context.sessionId || (context.request as any).sessionId;
        
        if (!sessionId) {
            console.warn('[AgenticMiddleware] Mandatory sessionId missing. Bypassing agentic layer to prevent data leakage and disk pollution.');
            await next();
            return;
        }

        const projectDir = await ensureProjectFiles(sessionId);
        const q = getQueues(sessionId);

        // Prepend system prompt with user context if available
        const userMessage = context.request.messages.find(m => m.role === 'user');
        const userContent = userMessage ? String(userMessage.content) : undefined;
        
        await prependSystemPrompt(context, userContent);

        // Task decomposition: Only perform if nowQueue is empty to prevent multi-turn duplication
        if (userContent && q.nowQueue.length === 0) {
            const steps = decomposeGoal(userContent);
            q.nowQueue.push(...steps);
        }

        await persistQueues(sessionId, projectDir);

        // Execute the pipeline
        await next();

        // Verification and queue update
        const responseContent = getResponseContent(context);
        if (responseContent) {
            const verifyResult = verifySelf(responseContent);

            if (verifyResult.startsWith('FAIL')) {
                q.improveQueue.push(verifyResult);
            }

            context['agenticQueues'] = getQueues(sessionId);
        }

        if (q.nowQueue.length > 0) {
            q.nowQueue.shift();
        }
        await persistQueues(sessionId, projectDir);
    }
}
