import fs from 'fs';
import path from 'path';
import { MOST_CAPABLE_AGENT_SYSTEM_PROMPT } from './prompts.js';
import type { Middleware, PipelineContext, NextFunction } from '../../pipeline/middleware.js';

const ENABLE_AGENTIC_MIDDLEWARE = process.env.ENABLE_AGENTIC_MIDDLEWARE === 'true';

interface QueueState {
    nowQueue: string[];
    nextQueue: string[];
    blockedQueue: string[];
    improveQueue: string[];
}

const queues = new Map<string, QueueState>();

function getQueues(sessionId: string): QueueState {
    if (!queues.has(sessionId)) {
        queues.set(sessionId, {
            nowQueue: [],
            nextQueue: [],
            blockedQueue: [],
            improveQueue: [],
        });
    }
    return queues.get(sessionId)!;
}

function persistQueues(sessionId: string, projectDir: string): void {
    const state = getQueues(sessionId);
    try {
        fs.writeFileSync(
            path.join(projectDir, 'queues.json'),
            JSON.stringify(state, null, 2),
            'utf-8',
        );
    } catch {
        // non-fatal: in-memory state is still maintained
    }
}

function ensureProjectFiles(sessionId: string): string {
    const projectDir = path.join(process.cwd(), 'projects', sessionId);
    fs.mkdirSync(projectDir, { recursive: true });

    const files: Record<string, string> = {
        'plan.md': '# Plan\n\n<!-- Auto-generated by Agentic Middleware -->\n',
        'tasks.md': '# Tasks\n\n<!-- Auto-generated by Agentic Middleware -->\n',
        'knowledge.md': '# Knowledge\n\n<!-- Auto-generated by Agentic Middleware -->\n',
    };

    for (const [name, content] of Object.entries(files)) {
        const filePath = path.join(projectDir, name);
        if (!fs.existsSync(filePath)) {
            fs.writeFileSync(filePath, content, 'utf-8');
        }
    }

    return projectDir;
}

function decomposeGoal(goal: string): string[] {
    // Minimal task decomposition: split on sentence boundaries or numbered lists
    const lines = goal
        .split(/\n+/)
        .map(l => l.replace(/^\s*\d+[.)]\s*/, '').trim())
        .filter(l => l.length > 0);
    return lines.length > 1 ? lines : [goal];
}

function prependSystemPrompt(context: PipelineContext): void {
    const messages = context.request.messages;
    if (!messages || messages.length === 0) return;

    const hasSystem = messages[0].role === 'system';
    if (hasSystem) {
        messages[0] = {
            ...messages[0],
            content: `${MOST_CAPABLE_AGENT_SYSTEM_PROMPT}\n\n${messages[0].content}`,
        };
    } else {
        messages.unshift({ role: 'system', content: MOST_CAPABLE_AGENT_SYSTEM_PROMPT });
    }
}

function getResponseContent(context: PipelineContext): string | undefined {
    return context.response?.choices?.[0]?.message?.content;
}

/**
 * Simple self-check: verifies the response is non-empty and contains no
 * obvious error markers without making an additional pipeline call.
 */
function verifySelf(content: string): string {
    if (!content || content.trim().length === 0) {
        return 'FAIL: empty response';
    }
    const errorPatterns = /\b(error|exception|failed|undefined|null)\b/i;
    if (errorPatterns.test(content.slice(0, 100))) {
        return 'FAIL: response starts with error indicator';
    }
    return 'PASS';
}

export class AgenticMiddleware implements Middleware {
    name = 'AgenticMiddleware';

    async execute(context: PipelineContext, next: NextFunction): Promise<void> {
        if (!ENABLE_AGENTIC_MIDDLEWARE) {
            await next();
            return;
        }

        const sessionId: string = context['sessionId'] ?? `session-${Date.now()}`;
        const projectDir = ensureProjectFiles(sessionId);
        const q = getQueues(sessionId);

        // Prepend system prompt
        prependSystemPrompt(context);

        // Task decomposition from user message
        const userMessage = context.request.messages.find(m => m.role === 'user');
        if (userMessage) {
            const steps = decomposeGoal(String(userMessage.content));
            q.nowQueue.push(...steps);
        }

        persistQueues(sessionId, projectDir);

        // Execute the pipeline for the main request
        await next();

        // Verification loop: simple self-check on the response
        const responseContent = getResponseContent(context);
        if (responseContent) {
            const verifyResult = verifySelf(responseContent);

            if (verifyResult.startsWith('FAIL')) {
                q.improveQueue.push(verifyResult);
            }

            // Annotate context with queue state for downstream consumers
            context['agenticQueues'] = getQueues(sessionId);
        }

        // Shift processed item now that the step is complete
        if (q.nowQueue.length > 0) {
            q.nowQueue.shift();
        }
        persistQueues(sessionId, projectDir);
    }
}
