export const config = {
  port: parseInt(process.env.PORT ?? '3000', 10),
  logLevel: process.env.LOG_LEVEL ?? 'info',
  memoryStorePath: process.env.MEMORY_STORE_PATH ?? './data/memory.json',
  providers: {
    cohere: process.env.CO_API_KEY,
    gemini: process.env.GEMINI_API_KEY,
    mistral: process.env.MISTRAL_API_KEY,
    zhipu: process.env.ZHIPU_API_KEY,
    cerebras: process.env.CEREBRAS_API_KEY,
    cloudflareToken: process.env.CLOUDFLARE_API_TOKEN,
    cloudflareAccountId: process.env.CLOUDFLARE_ACCOUNT_ID,
    github: process.env.GITHUB_TOKEN,
    groq: process.env.GROQ_API_KEY,
    huggingface: process.env.HF_TOKEN,
    kluster: process.env.KLUSTER_API_KEY,
    llm7: process.env.LLM7_API_KEY,
    nvidia: process.env.NVIDIA_API_KEY,
    ollama: process.env.OLLAMA_API_KEY,
    openrouter: process.env.OPENROUTER_API_KEY,
    siliconflow: process.env.SILICONFLOW_API_KEY,
  },
};
